package com.raptor.customfence_fabric.init;

import com.raptor.customfence_fabric.Main;
import com.raptor.customfence_fabric.blocks.*;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.block.*;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroups;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.util.Identifier;

public class ModBlocksMetalFence {

    public static final Block  COBBLESTONE_COPPER_MANSION_FENCE = registerBlock("cobblestone_copper_mansion_fence", new MetalFence(Oxidizable.OxidationLevel.UNAFFECTED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_copper_mansion_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));
    public static final Block  COBBLESTONE_EXPOSED_COPPER_MANSION_FENCE = registerBlock("cobblestone_exposed_copper_mansion_fence", new MetalFence(Oxidizable.OxidationLevel.EXPOSED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_exposed_copper_mansion_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));
    public static final Block  COBBLESTONE_WEATHERED_COPPER_MANSION_FENCE = registerBlock("cobblestone_weathered_copper_mansion_fence", new MetalFence(Oxidizable.OxidationLevel.WEATHERED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_weathered_copper_mansion_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));
    public static final Block  COBBLESTONE_OXIDIZED_COPPER_MANSION_FENCE = registerBlock("cobblestone_oxidized_copper_mansion_fence", new MetalFence(Oxidizable.OxidationLevel.OXIDIZED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_oxidized_copper_mansion_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));

    public static final Block  COPPER_MANSION_FENCE_GATE = registerBlock("copper_mansion_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.UNAFFECTED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "copper_mansion_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));
    public static final Block  EXPOSED_COPPER_MANSION_FENCE_GATE = registerBlock("exposed_copper_mansion_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.EXPOSED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "exposed_copper_mansion_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));
    public static final Block  WEATHERED_COPPER_MANSION_FENCE_GATE = registerBlock("weathered_copper_mansion_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.WEATHERED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "weathered_copper_mansion_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));
    public static final Block  OXIDIZED_COPPER_MANSION_FENCE_GATE = registerBlock("oxidized_copper_mansion_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.OXIDIZED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "oxidized_copper_mansion_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));

    public static final Block  COBBLESTONE_WAXED_COPPER_MANSION_FENCE = registerBlock("cobblestone_waxed_copper_mansion_fence", new MetalFence(Oxidizable.OxidationLevel.UNAFFECTED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_waxed_copper_mansion_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));
    public static final Block  COBBLESTONE_WAXED_EXPOSED_COPPER_MANSION_FENCE = registerBlock("cobblestone_waxed_exposed_copper_mansion_fence", new MetalFence(Oxidizable.OxidationLevel.EXPOSED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_waxed_exposed_copper_mansion_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));
    public static final Block  COBBLESTONE_WAXED_WEATHERED_COPPER_MANSION_FENCE = registerBlock("cobblestone_waxed_weathered_copper_mansion_fence", new MetalFence(Oxidizable.OxidationLevel.WEATHERED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_waxed_weathered_copper_mansion_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));
    public static final Block  COBBLESTONE_WAXED_OXIDIZED_COPPER_MANSION_FENCE = registerBlock("cobblestone_waxed_oxidized_copper_mansion_fence", new MetalFence(Oxidizable.OxidationLevel.OXIDIZED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_waxed_oxidized_copper_mansion_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));

    public static final Block  WAXED_COPPER_MANSION_FENCE_GATE = registerBlock("waxed_copper_mansion_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.UNAFFECTED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "waxed_copper_mansion_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));
    public static final Block  WAXED_EXPOSED_COPPER_MANSION_FENCE_GATE = registerBlock("waxed_exposed_copper_mansion_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.EXPOSED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "waxed_exposed_copper_mansion_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));
    public static final Block  WAXED_WEATHERED_COPPER_MANSION_FENCE_GATE = registerBlock("waxed_weathered_copper_mansion_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.WEATHERED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "waxed_weathered_copper_mansion_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));
    public static final Block  WAXED_OXIDIZED_COPPER_MANSION_FENCE_GATE = registerBlock("waxed_oxidized_copper_mansion_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.OXIDIZED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "waxed_oxidized_copper_mansion_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));


    public static final Block  COBBLESTONE_IRON_MANSION_FENCE = registerBlock("cobblestone_iron_mansion_fence", new MetalFence(Oxidizable.OxidationLevel.UNAFFECTED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_iron_mansion_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));
    public static final Block  COBBLESTONE_EXPOSED_IRON_MANSION_FENCE = registerBlock("cobblestone_exposed_iron_mansion_fence", new MetalFence(Oxidizable.OxidationLevel.EXPOSED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_exposed_iron_mansion_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));
    public static final Block  COBBLESTONE_WEATHERED_IRON_MANSION_FENCE = registerBlock("cobblestone_weathered_iron_mansion_fence", new MetalFence(Oxidizable.OxidationLevel.WEATHERED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_weathered_iron_mansion_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));
    public static final Block  COBBLESTONE_OXIDIZED_IRON_MANSION_FENCE = registerBlock("cobblestone_oxidized_iron_mansion_fence", new MetalFence(Oxidizable.OxidationLevel.OXIDIZED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_oxidized_iron_mansion_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));

    public static final Block  IRON_MANSION_FENCE_GATE = registerBlock("iron_mansion_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.UNAFFECTED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "iron_mansion_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));
    public static final Block  EXPOSED_IRON_MANSION_FENCE_GATE = registerBlock("exposed_iron_mansion_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.EXPOSED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "exposed_iron_mansion_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));
    public static final Block  WEATHERED_IRON_MANSION_FENCE_GATE = registerBlock("weathered_iron_mansion_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.WEATHERED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "weathered_iron_mansion_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));
    public static final Block  OXIDIZED_IRON_MANSION_FENCE_GATE = registerBlock("oxidized_iron_mansion_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.OXIDIZED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "oxidized_iron_mansion_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));

    public static final Block  COBBLESTONE_WAXED_IRON_MANSION_FENCE = registerBlock("cobblestone_waxed_iron_mansion_fence", new MetalFence(Oxidizable.OxidationLevel.UNAFFECTED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_waxed_iron_mansion_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));
    public static final Block  COBBLESTONE_WAXED_EXPOSED_IRON_MANSION_FENCE = registerBlock("cobblestone_waxed_exposed_iron_mansion_fence", new MetalFence(Oxidizable.OxidationLevel.EXPOSED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_waxed_exposed_iron_mansion_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));
    public static final Block  COBBLESTONE_WAXED_WEATHERED_IRON_MANSION_FENCE = registerBlock("cobblestone_waxed_weathered_iron_mansion_fence", new MetalFence(Oxidizable.OxidationLevel.WEATHERED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_waxed_weathered_iron_mansion_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));
    public static final Block  COBBLESTONE_WAXED_OXIDIZED_IRON_MANSION_FENCE = registerBlock("cobblestone_waxed_oxidized_iron_mansion_fence", new MetalFence(Oxidizable.OxidationLevel.OXIDIZED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_waxed_oxidized_iron_mansion_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));

    public static final Block  WAXED_IRON_MANSION_FENCE_GATE = registerBlock("waxed_iron_mansion_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.UNAFFECTED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "waxed_iron_mansion_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));
    public static final Block  WAXED_EXPOSED_IRON_MANSION_FENCE_GATE = registerBlock("waxed_exposed_iron_mansion_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.EXPOSED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "waxed_exposed_iron_mansion_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));
    public static final Block  WAXED_WEATHERED_IRON_MANSION_FENCE_GATE = registerBlock("waxed_weathered_iron_mansion_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.WEATHERED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "waxed_weathered_iron_mansion_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));
    public static final Block  WAXED_OXIDIZED_IRON_MANSION_FENCE_GATE = registerBlock("waxed_oxidized_iron_mansion_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.OXIDIZED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "waxed_oxidized_iron_mansion_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));


    public static final Block  COBBLESTONE_GOLD_MANSION_FENCE = registerBlock("cobblestone_gold_mansion_fence", new MetalFence(Oxidizable.OxidationLevel.UNAFFECTED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_gold_mansion_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));
    public static final Block  GOLD_MANSION_FENCE_GATE = registerBlock("gold_mansion_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.UNAFFECTED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "gold_mansion_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));


    public static final Block  COBBLESTONE_COPPER_MESH_FENCE = registerBlock("cobblestone_copper_mesh_fence", new MetalFence(Oxidizable.OxidationLevel.UNAFFECTED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_copper_mesh_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));
    public static final Block  COBBLESTONE_EXPOSED_COPPER_MESH_FENCE = registerBlock("cobblestone_exposed_copper_mesh_fence", new MetalFence(Oxidizable.OxidationLevel.EXPOSED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_exposed_copper_mesh_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));
    public static final Block  COBBLESTONE_WEATHERED_COPPER_MESH_FENCE = registerBlock("cobblestone_weathered_copper_mesh_fence", new MetalFence(Oxidizable.OxidationLevel.WEATHERED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_weathered_copper_mesh_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));
    public static final Block  COBBLESTONE_OXIDIZED_COPPER_MESH_FENCE = registerBlock("cobblestone_oxidized_copper_mesh_fence", new MetalFence(Oxidizable.OxidationLevel.OXIDIZED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_oxidized_copper_mesh_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));

    public static final Block  COPPER_MESH_FENCE_GATE = registerBlock("copper_mesh_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.UNAFFECTED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "copper_mesh_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));
    public static final Block  EXPOSED_COPPER_MESH_FENCE_GATE = registerBlock("exposed_copper_mesh_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.EXPOSED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "exposed_copper_mesh_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));
    public static final Block  WEATHERED_COPPER_MESH_FENCE_GATE = registerBlock("weathered_copper_mesh_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.WEATHERED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "weathered_copper_mesh_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));
    public static final Block  OXIDIZED_COPPER_MESH_FENCE_GATE = registerBlock("oxidized_copper_mesh_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.OXIDIZED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "oxidized_copper_mesh_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));

    public static final Block  COBBLESTONE_WAXED_COPPER_MESH_FENCE = registerBlock("cobblestone_waxed_copper_mesh_fence", new MetalFence(Oxidizable.OxidationLevel.UNAFFECTED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_waxed_copper_mesh_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));
    public static final Block  COBBLESTONE_WAXED_EXPOSED_COPPER_MESH_FENCE = registerBlock("cobblestone_waxed_exposed_copper_mesh_fence", new MetalFence(Oxidizable.OxidationLevel.EXPOSED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_waxed_exposed_copper_mesh_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));
    public static final Block  COBBLESTONE_WAXED_WEATHERED_COPPER_MESH_FENCE = registerBlock("cobblestone_waxed_weathered_copper_mesh_fence", new MetalFence(Oxidizable.OxidationLevel.WEATHERED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_waxed_weathered_copper_mesh_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));
    public static final Block  COBBLESTONE_WAXED_OXIDIZED_COPPER_MESH_FENCE = registerBlock("cobblestone_waxed_oxidized_copper_mesh_fence", new MetalFence(Oxidizable.OxidationLevel.OXIDIZED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_waxed_oxidized_copper_mesh_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));

    public static final Block  WAXED_COPPER_MESH_FENCE_GATE = registerBlock("waxed_copper_mesh_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.UNAFFECTED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "waxed_copper_mesh_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));
    public static final Block  WAXED_EXPOSED_COPPER_MESH_FENCE_GATE = registerBlock("waxed_exposed_copper_mesh_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.EXPOSED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "waxed_exposed_copper_mesh_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));
    public static final Block  WAXED_WEATHERED_COPPER_MESH_FENCE_GATE = registerBlock("waxed_weathered_copper_mesh_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.WEATHERED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "waxed_weathered_copper_mesh_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));
    public static final Block  WAXED_OXIDIZED_COPPER_MESH_FENCE_GATE = registerBlock("waxed_oxidized_copper_mesh_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.OXIDIZED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "waxed_oxidized_copper_mesh_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));


    public static final Block  COBBLESTONE_IRON_MESH_FENCE = registerBlock("cobblestone_iron_mesh_fence", new MetalFence(Oxidizable.OxidationLevel.UNAFFECTED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_iron_mesh_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));
    public static final Block  COBBLESTONE_EXPOSED_IRON_MESH_FENCE = registerBlock("cobblestone_exposed_iron_mesh_fence", new MetalFence(Oxidizable.OxidationLevel.EXPOSED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_exposed_iron_mesh_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));
    public static final Block  COBBLESTONE_WEATHERED_IRON_MESH_FENCE = registerBlock("cobblestone_weathered_iron_mesh_fence", new MetalFence(Oxidizable.OxidationLevel.WEATHERED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_weathered_iron_mesh_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));
    public static final Block  COBBLESTONE_OXIDIZED_IRON_MESH_FENCE = registerBlock("cobblestone_oxidized_iron_mesh_fence", new MetalFence(Oxidizable.OxidationLevel.OXIDIZED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_oxidized_iron_mesh_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));

    public static final Block  IRON_MESH_FENCE_GATE = registerBlock("iron_mesh_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.UNAFFECTED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "iron_mesh_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));
    public static final Block  EXPOSED_IRON_MESH_FENCE_GATE = registerBlock("exposed_iron_mesh_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.EXPOSED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "exposed_iron_mesh_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));
    public static final Block  WEATHERED_IRON_MESH_FENCE_GATE = registerBlock("weathered_iron_mesh_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.WEATHERED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "weathered_iron_mesh_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));
    public static final Block  OXIDIZED_IRON_MESH_FENCE_GATE = registerBlock("oxidized_iron_mesh_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.OXIDIZED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "oxidized_iron_mesh_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));

    public static final Block  COBBLESTONE_WAXED_IRON_MESH_FENCE = registerBlock("cobblestone_waxed_iron_mesh_fence", new MetalFence(Oxidizable.OxidationLevel.UNAFFECTED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_waxed_iron_mesh_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));
    public static final Block  COBBLESTONE_WAXED_EXPOSED_IRON_MESH_FENCE = registerBlock("cobblestone_waxed_exposed_iron_mesh_fence", new MetalFence(Oxidizable.OxidationLevel.EXPOSED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_waxed_exposed_iron_mesh_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));
    public static final Block  COBBLESTONE_WAXED_WEATHERED_IRON_MESH_FENCE = registerBlock("cobblestone_waxed_weathered_iron_mesh_fence", new MetalFence(Oxidizable.OxidationLevel.WEATHERED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_waxed_weathered_iron_mesh_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));
    public static final Block  COBBLESTONE_WAXED_OXIDIZED_IRON_MESH_FENCE = registerBlock("cobblestone_waxed_oxidized_iron_mesh_fence", new MetalFence(Oxidizable.OxidationLevel.OXIDIZED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_waxed_oxidized_iron_mesh_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));

    public static final Block  WAXED_IRON_MESH_FENCE_GATE = registerBlock("waxed_iron_mesh_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.UNAFFECTED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "waxed_iron_mesh_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));
    public static final Block  WAXED_EXPOSED_IRON_MESH_FENCE_GATE = registerBlock("waxed_exposed_iron_mesh_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.EXPOSED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "waxed_exposed_iron_mesh_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));
    public static final Block  WAXED_WEATHERED_IRON_MESH_FENCE_GATE = registerBlock("waxed_weathered_iron_mesh_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.WEATHERED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "waxed_weathered_iron_mesh_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));
    public static final Block  WAXED_OXIDIZED_IRON_MESH_FENCE_GATE = registerBlock("waxed_oxidized_iron_mesh_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.OXIDIZED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "waxed_oxidized_iron_mesh_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));


    public static final Block  COBBLESTONE_GOLD_MESH_FENCE = registerBlock("cobblestone_gold_mesh_fence", new MetalFence(Oxidizable.OxidationLevel.UNAFFECTED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "cobblestone_gold_mesh_fence"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.STONE)));
    public static final Block  GOLD_MESH_FENCE_GATE = registerBlock("gold_mesh_fence_gate", new MetalFenceGate(Oxidizable.OxidationLevel.UNAFFECTED, AbstractBlock.Settings.create().registryKey(RegistryKey.of(RegistryKeys.BLOCK, Identifier.of(Main.MOD_ID, "gold_mesh_fence_gate"))).strength(3.0F, 6.0F).sounds(BlockSoundGroup.COPPER), WoodType.BIRCH));


    public static Block registerBlock(String name, Block block) {
        registerBlockItem(name, block);
        return Registry.register(Registries.BLOCK, Identifier.of(Main.MOD_ID, name), block);
    }

    public static void registerBlockItem(String name, Block block) {
        Registry.register(Registries.ITEM, Identifier.of(Main.MOD_ID, name),
                new BlockItem(block, new Item.Settings().registryKey(RegistryKey.of(RegistryKeys.ITEM, Identifier.of(Main.MOD_ID, name))).useBlockPrefixedTranslationKey()));
    }

    public static void registerModBlocks() {
        ItemGroupEvents.modifyEntriesEvent(ItemGroups.BUILDING_BLOCKS).register(entries -> {
            entries.add(ModBlocksMetalFence.COBBLESTONE_COPPER_MANSION_FENCE);
        });
    }

}
