package com.raptor.customfence_fabric.init;

import com.raptor.customfence_fabric.Main;
import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.minecraft.block.Block;
import net.minecraft.item.*;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;

import java.util.ArrayList;


public class ModItemGroup {


    public static final RegistryKey<ItemGroup> CUSTOMFENCE_WOOD_FENCE = RegistryKey.of(RegistryKeys.ITEM_GROUP, Identifier.of(Main.MOD_ID, "customfence_1_wooden_fence"));
    public static final RegistryKey<ItemGroup> CUSTOMFENCE_WALL = RegistryKey.of(RegistryKeys.ITEM_GROUP, Identifier.of(Main.MOD_ID, "customfence_2_wall"));
    public static final RegistryKey<ItemGroup> CUSTOMFENCE_METAL_FENCE = RegistryKey.of(RegistryKeys.ITEM_GROUP, Identifier.of(Main.MOD_ID, "customfence_3_metal_fence"));
    public static final RegistryKey<ItemGroup> CUSTOMFENCE = RegistryKey.of(RegistryKeys.ITEM_GROUP, Identifier.of(Main.MOD_ID, "customfence"));

    public static ArrayList<Block> listOfWoodFenceBlocks() {

        ArrayList<Block> WOOD_FENCE_BLOCK_LIST = new ArrayList<Block>();

        //BEGIN WOODENFENCEGATES

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_CLASSIC_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_WILDLIFE_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_PLANK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_CRISSCROSS_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_CLASSIC_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_WILDLIFE_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_PLANK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_CRISSCROSS_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_CLASSIC_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_WILDLIFE_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_PLANK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_CRISSCROSS_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CLASSIC_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_WILDLIFE_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_PLANK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CRISSCROSS_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_CLASSIC_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_WILDLIFE_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_PLANK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_CRISSCROSS_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_CLASSIC_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_WILDLIFE_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_PLANK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_CRISSCROSS_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_CLASSIC_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_WILDLIFE_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_PLANK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_CRISSCROSS_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_CLASSIC_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_WILDLIFE_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_PLANK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_CRISSCROSS_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_CLASSIC_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_WILDLIFE_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_PLANK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_CRISSCROSS_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_CLASSIC_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_WILDLIFE_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_PLANK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_CRISSCROSS_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_CLASSIC_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_WILDLIFE_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_PLANK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_CRISSCROSS_GATE);

        //END WOODENFENCEGATES AND BEGIN WOODENFENCES

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_OAK_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_OAK_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_OAK_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_OAK_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_OAK_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_OAK_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_OAK_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_OAK_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_OAK_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_OAK_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_OAK_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_OAK_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_OAK_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_OAK_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_SPRUCE_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_SPRUCE_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_SPRUCE_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_SPRUCE_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_SPRUCE_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_SPRUCE_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_SPRUCE_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_SPRUCE_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_SPRUCE_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_SPRUCE_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_SPRUCE_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_SPRUCE_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_SPRUCE_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_SPRUCE_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_BIRCH_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_BIRCH_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_BIRCH_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_BIRCH_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_BIRCH_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_BIRCH_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_BIRCH_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_BIRCH_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_BIRCH_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_BIRCH_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_BIRCH_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_BIRCH_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_BIRCH_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_BIRCH_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_OAK_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_OAK_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_OAK_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_OAK_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_OAK_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_OAK_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_OAK_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_OAK_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_OAK_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_OAK_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_OAK_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_OAK_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_OAK_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_OAK_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_BIRCH_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_BIRCH_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_BIRCH_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_BIRCH_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_BIRCH_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_BIRCH_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_BIRCH_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_BIRCH_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_BIRCH_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_BIRCH_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_BIRCH_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_BIRCH_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_BIRCH_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_BIRCH_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_SPRUCE_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_SPRUCE_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_SPRUCE_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_SPRUCE_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_SPRUCE_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_SPRUCE_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_SPRUCE_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_SPRUCE_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_SPRUCE_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_SPRUCE_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_SPRUCE_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_SPRUCE_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_SPRUCE_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_SPRUCE_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_SPRUCE_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_SPRUCE_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_SPRUCE_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_SPRUCE_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_SPRUCE_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_SPRUCE_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_SPRUCE_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_SPRUCE_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_SPRUCE_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_SPRUCE_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_SPRUCE_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_SPRUCE_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_SPRUCE_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_SPRUCE_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_DARKOAK_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_DARKOAK_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_DARKOAK_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_DARKOAK_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_DARKOAK_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_DARKOAK_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_DARKOAK_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_DARKOAK_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_DARKOAK_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_DARKOAK_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_DARKOAK_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_DARKOAK_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_DARKOAK_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_DARKOAK_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_OAK_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_OAK_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_OAK_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_OAK_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_OAK_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_OAK_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_OAK_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_OAK_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_OAK_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_OAK_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_OAK_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_OAK_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_OAK_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_OAK_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_DARKOAK_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_DARKOAK_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_DARKOAK_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_DARKOAK_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_DARKOAK_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_DARKOAK_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_DARKOAK_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_DARKOAK_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_DARKOAK_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_DARKOAK_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_DARKOAK_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_DARKOAK_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_DARKOAK_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_DARKOAK_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_JUNGLE_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_JUNGLE_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_JUNGLE_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_JUNGLE_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_JUNGLE_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_JUNGLE_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_JUNGLE_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_JUNGLE_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_JUNGLE_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_JUNGLE_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_JUNGLE_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_JUNGLE_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_JUNGLE_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_JUNGLE_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_DARKOAK_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_DARKOAK_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_DARKOAK_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_DARKOAK_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_DARKOAK_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_DARKOAK_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_DARKOAK_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_DARKOAK_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_DARKOAK_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_DARKOAK_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_DARKOAK_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_DARKOAK_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_DARKOAK_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_DARKOAK_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_JUNGLE_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_JUNGLE_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_JUNGLE_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_JUNGLE_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_JUNGLE_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_JUNGLE_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_JUNGLE_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_JUNGLE_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_JUNGLE_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_JUNGLE_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_JUNGLE_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_JUNGLE_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_JUNGLE_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_JUNGLE_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_ACACIA_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_ACACIA_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_ACACIA_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_ACACIA_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_ACACIA_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_ACACIA_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_ACACIA_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_ACACIA_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_ACACIA_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_ACACIA_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_ACACIA_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_ACACIA_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_ACACIA_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_ACACIA_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_BIRCH_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_BIRCH_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_BIRCH_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_BIRCH_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_BIRCH_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_BIRCH_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_BIRCH_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_BIRCH_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_BIRCH_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_BIRCH_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_BIRCH_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_BIRCH_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_BIRCH_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_BIRCH_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_ACACIA_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_ACACIA_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_ACACIA_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_ACACIA_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_ACACIA_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_ACACIA_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_ACACIA_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_ACACIA_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_ACACIA_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_ACACIA_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_ACACIA_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_ACACIA_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_ACACIA_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_ACACIA_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_BIRCH_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_BIRCH_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_BIRCH_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_BIRCH_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_BIRCH_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_BIRCH_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_BIRCH_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_BIRCH_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_BIRCH_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_BIRCH_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_BIRCH_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_BIRCH_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_BIRCH_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_BIRCH_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_JUNGLE_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_JUNGLE_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_JUNGLE_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_JUNGLE_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_JUNGLE_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_JUNGLE_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_JUNGLE_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_JUNGLE_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_JUNGLE_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_JUNGLE_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_JUNGLE_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_JUNGLE_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_JUNGLE_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_JUNGLE_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_BIRCH_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_BIRCH_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_BIRCH_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_BIRCH_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_BIRCH_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_BIRCH_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_BIRCH_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_BIRCH_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_BIRCH_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_BIRCH_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_BIRCH_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_BIRCH_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_BIRCH_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_BIRCH_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_WARPED_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_WARPED_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_WARPED_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_WARPED_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_WARPED_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_WARPED_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_WARPED_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_WARPED_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_WARPED_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_WARPED_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_WARPED_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_WARPED_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_WARPED_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_WARPED_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_OAK_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_OAK_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_OAK_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_OAK_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_OAK_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_OAK_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_OAK_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_OAK_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_OAK_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_OAK_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_OAK_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_OAK_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_OAK_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_OAK_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_WARPED_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_WARPED_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_WARPED_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_WARPED_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_WARPED_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_WARPED_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_WARPED_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_WARPED_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_WARPED_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_WARPED_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_WARPED_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_WARPED_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_WARPED_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_WARPED_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_SPRUCE_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_SPRUCE_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_SPRUCE_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_SPRUCE_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_SPRUCE_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_SPRUCE_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_SPRUCE_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_SPRUCE_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_SPRUCE_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_SPRUCE_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_SPRUCE_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_SPRUCE_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_SPRUCE_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_SPRUCE_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_WARPED_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_WARPED_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_WARPED_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_WARPED_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_WARPED_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_WARPED_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_WARPED_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_WARPED_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_WARPED_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_WARPED_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_WARPED_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_WARPED_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_WARPED_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_WARPED_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_JUNGLE_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_JUNGLE_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_JUNGLE_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_JUNGLE_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_JUNGLE_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_JUNGLE_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_JUNGLE_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_JUNGLE_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_JUNGLE_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_JUNGLE_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_JUNGLE_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_JUNGLE_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_JUNGLE_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_JUNGLE_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CRIMSON_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CRIMSON_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CRIMSON_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CRIMSON_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CRIMSON_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CRIMSON_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CRIMSON_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CRIMSON_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CRIMSON_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CRIMSON_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CRIMSON_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CRIMSON_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CRIMSON_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CRIMSON_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_OAK_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_OAK_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_OAK_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_OAK_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_OAK_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_OAK_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_OAK_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_OAK_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_OAK_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_OAK_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_OAK_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_OAK_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_OAK_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_OAK_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_CRIMSON_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_CRIMSON_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_CRIMSON_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_CRIMSON_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_CRIMSON_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_CRIMSON_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_CRIMSON_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_CRIMSON_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_CRIMSON_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_CRIMSON_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_CRIMSON_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_CRIMSON_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_CRIMSON_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_CRIMSON_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_DARKOAK_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_DARKOAK_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_DARKOAK_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_DARKOAK_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_DARKOAK_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_DARKOAK_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_DARKOAK_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_DARKOAK_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_DARKOAK_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_DARKOAK_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_DARKOAK_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_DARKOAK_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_DARKOAK_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_DARKOAK_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_CRIMSON_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_CRIMSON_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_CRIMSON_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_CRIMSON_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_CRIMSON_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_CRIMSON_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_CRIMSON_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_CRIMSON_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_CRIMSON_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_CRIMSON_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_CRIMSON_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_CRIMSON_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_CRIMSON_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_CRIMSON_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_OAK_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_OAK_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_OAK_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_OAK_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_OAK_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_OAK_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_OAK_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_OAK_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_OAK_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_OAK_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_OAK_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_OAK_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_OAK_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_OAK_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_MANGROVE_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_MANGROVE_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_MANGROVE_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_MANGROVE_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_MANGROVE_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_MANGROVE_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_MANGROVE_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_MANGROVE_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_MANGROVE_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_MANGROVE_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_MANGROVE_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_MANGROVE_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_MANGROVE_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_MANGROVE_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_BIRCH_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_BIRCH_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_BIRCH_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_BIRCH_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_BIRCH_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_BIRCH_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_BIRCH_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_BIRCH_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_BIRCH_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_BIRCH_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_BIRCH_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_BIRCH_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_BIRCH_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_BIRCH_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_MANGROVE_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_MANGROVE_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_MANGROVE_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_MANGROVE_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_MANGROVE_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_MANGROVE_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_MANGROVE_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_MANGROVE_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_MANGROVE_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_MANGROVE_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_MANGROVE_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_MANGROVE_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_MANGROVE_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BIRCH_MANGROVE_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_JUNGLE_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_JUNGLE_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_JUNGLE_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_JUNGLE_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_JUNGLE_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_JUNGLE_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_JUNGLE_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_JUNGLE_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_JUNGLE_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_JUNGLE_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_JUNGLE_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_JUNGLE_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_JUNGLE_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_JUNGLE_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_MANGROVE_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_MANGROVE_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_MANGROVE_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_MANGROVE_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_MANGROVE_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_MANGROVE_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_MANGROVE_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_MANGROVE_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_MANGROVE_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_MANGROVE_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_MANGROVE_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_MANGROVE_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_MANGROVE_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_MANGROVE_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_DARKOAK_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_DARKOAK_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_DARKOAK_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_DARKOAK_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_DARKOAK_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_DARKOAK_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_DARKOAK_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_DARKOAK_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_DARKOAK_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_DARKOAK_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_DARKOAK_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_DARKOAK_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_DARKOAK_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_DARKOAK_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_MANGROVE_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_MANGROVE_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_MANGROVE_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_MANGROVE_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_MANGROVE_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_MANGROVE_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_MANGROVE_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_MANGROVE_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_MANGROVE_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_MANGROVE_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_MANGROVE_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_MANGROVE_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_MANGROVE_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.DARKOAK_MANGROVE_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_WARPED_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_WARPED_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_WARPED_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_WARPED_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_WARPED_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_WARPED_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_WARPED_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_WARPED_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_WARPED_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_WARPED_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_WARPED_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_WARPED_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_WARPED_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_WARPED_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_MANGROVE_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_MANGROVE_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_MANGROVE_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_MANGROVE_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_MANGROVE_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_MANGROVE_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_MANGROVE_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_MANGROVE_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_MANGROVE_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_MANGROVE_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_MANGROVE_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_MANGROVE_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_MANGROVE_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_MANGROVE_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_OAK_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_OAK_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_OAK_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_OAK_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_OAK_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_OAK_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_OAK_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_OAK_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_OAK_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_OAK_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_OAK_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_OAK_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_OAK_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_OAK_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_BAMBOO_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_BAMBOO_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_BAMBOO_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_BAMBOO_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_BAMBOO_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_BAMBOO_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_BAMBOO_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_BAMBOO_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_BAMBOO_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_BAMBOO_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_BAMBOO_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_BAMBOO_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_BAMBOO_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.OAK_BAMBOO_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_SPRUCE_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_SPRUCE_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_SPRUCE_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_SPRUCE_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_SPRUCE_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_SPRUCE_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_SPRUCE_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_SPRUCE_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_SPRUCE_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_SPRUCE_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_SPRUCE_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_SPRUCE_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_SPRUCE_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_SPRUCE_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_BAMBOO_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_BAMBOO_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_BAMBOO_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_BAMBOO_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_BAMBOO_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_BAMBOO_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_BAMBOO_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_BAMBOO_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_BAMBOO_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_BAMBOO_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_BAMBOO_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_BAMBOO_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_BAMBOO_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.SPRUCE_BAMBOO_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_JUNGLE_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_JUNGLE_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_JUNGLE_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_JUNGLE_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_JUNGLE_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_JUNGLE_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_JUNGLE_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_JUNGLE_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_JUNGLE_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_JUNGLE_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_JUNGLE_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_JUNGLE_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_JUNGLE_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_JUNGLE_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_BAMBOO_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_BAMBOO_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_BAMBOO_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_BAMBOO_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_BAMBOO_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_BAMBOO_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_BAMBOO_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_BAMBOO_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_BAMBOO_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_BAMBOO_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_BAMBOO_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_BAMBOO_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_BAMBOO_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_BAMBOO_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_ACACIA_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_ACACIA_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_ACACIA_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_ACACIA_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_ACACIA_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_ACACIA_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_ACACIA_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_ACACIA_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_ACACIA_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_ACACIA_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_ACACIA_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_ACACIA_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_ACACIA_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_ACACIA_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_BAMBOO_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_BAMBOO_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_BAMBOO_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_BAMBOO_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_BAMBOO_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_BAMBOO_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_BAMBOO_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_BAMBOO_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_BAMBOO_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_BAMBOO_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_BAMBOO_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_BAMBOO_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_BAMBOO_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_BAMBOO_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_WARPED_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_WARPED_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_WARPED_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_WARPED_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_WARPED_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_WARPED_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_WARPED_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_WARPED_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_WARPED_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_WARPED_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_WARPED_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_WARPED_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_WARPED_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_WARPED_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_BAMBOO_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_BAMBOO_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_BAMBOO_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_BAMBOO_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_BAMBOO_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_BAMBOO_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_BAMBOO_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_BAMBOO_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_BAMBOO_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_BAMBOO_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_BAMBOO_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_BAMBOO_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_BAMBOO_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.WARPED_BAMBOO_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_JUNGLE_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_JUNGLE_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_JUNGLE_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_JUNGLE_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_JUNGLE_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_JUNGLE_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_JUNGLE_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_JUNGLE_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_JUNGLE_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_JUNGLE_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_JUNGLE_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_JUNGLE_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_JUNGLE_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_JUNGLE_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CHERRY_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CHERRY_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CHERRY_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CHERRY_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CHERRY_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CHERRY_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CHERRY_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CHERRY_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CHERRY_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CHERRY_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CHERRY_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CHERRY_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CHERRY_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.JUNGLE_CHERRY_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_ACACIA_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_ACACIA_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_ACACIA_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_ACACIA_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_ACACIA_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_ACACIA_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_ACACIA_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_ACACIA_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_ACACIA_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_ACACIA_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_ACACIA_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_ACACIA_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_ACACIA_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_ACACIA_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_CHERRY_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_CHERRY_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_CHERRY_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_CHERRY_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_CHERRY_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_CHERRY_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_CHERRY_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_CHERRY_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_CHERRY_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_CHERRY_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_CHERRY_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_CHERRY_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_CHERRY_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.ACACIA_CHERRY_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_MANGROVE_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_MANGROVE_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_MANGROVE_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_MANGROVE_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_MANGROVE_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_MANGROVE_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_MANGROVE_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_MANGROVE_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_MANGROVE_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_MANGROVE_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_MANGROVE_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_MANGROVE_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_MANGROVE_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_MANGROVE_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_CHERRY_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_CHERRY_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_CHERRY_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_CHERRY_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_CHERRY_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_CHERRY_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_CHERRY_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_CHERRY_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_CHERRY_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_CHERRY_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_CHERRY_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_CHERRY_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_CHERRY_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.MANGROVE_CHERRY_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_BAMBOO_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_BAMBOO_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_BAMBOO_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_BAMBOO_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_BAMBOO_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_BAMBOO_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_BAMBOO_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_BAMBOO_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_BAMBOO_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_BAMBOO_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_BAMBOO_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_BAMBOO_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_BAMBOO_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_BAMBOO_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_CHERRY_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_CHERRY_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_CHERRY_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_CHERRY_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_CHERRY_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_CHERRY_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_CHERRY_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_CHERRY_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_CHERRY_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_CHERRY_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_CHERRY_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_CHERRY_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_CHERRY_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.BAMBOO_CHERRY_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_CRIMSON_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_CRIMSON_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_CRIMSON_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_CRIMSON_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_CRIMSON_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_CRIMSON_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_CRIMSON_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_CRIMSON_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_CRIMSON_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_CRIMSON_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_CRIMSON_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_CRIMSON_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_CRIMSON_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CHERRY_CRIMSON_SPIRE_GATE);

        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_CHERRY_CLASSIC);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_CHERRY_WILDLIFE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_CHERRY_DECORATION);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_CHERRY_DECORATION_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_CHERRY_PLANK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_CHERRY_GARDEN);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_CHERRY_GARDEN_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_CHERRY_BOLLARD);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_CHERRY_BOLLARD_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_CHERRY_STICK);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_CHERRY_STICK_GATE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_CHERRY_CRISSCROSS);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_CHERRY_SPIRE);
        WOOD_FENCE_BLOCK_LIST.add(ModBlocks.CRIMSON_CHERRY_SPIRE_GATE);

        //END WOODENFENCES

        return WOOD_FENCE_BLOCK_LIST;
    }

    public static ArrayList<Block> listOfWallBlocks() {

        ArrayList<Block> WALL_BLOCK_LIST = new ArrayList<Block>();
        
        //BEGIN STONEWALLS

        WALL_BLOCK_LIST.add(ModBlocks.COBBLESTONE_MODERN);
        WALL_BLOCK_LIST.add(ModBlocks.COBBLESTONE_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.COBBLESTONE_CASTLE);

        WALL_BLOCK_LIST.add(ModBlocks.MOSSY_COBBLESTONE_MODERN);
        WALL_BLOCK_LIST.add(ModBlocks.MOSSY_COBBLESTONE_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.MOSSY_COBBLESTONE_CASTLE);

        WALL_BLOCK_LIST.add(ModBlocks.STONE_MODERN);
        WALL_BLOCK_LIST.add(ModBlocks.STONE_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.STONE_CASTLE);

        WALL_BLOCK_LIST.add(ModBlocks.STONE_BRICKS_MODERN);
        WALL_BLOCK_LIST.add(ModBlocks.STONE_BRICKS_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.STONE_BRICKS_CASTLE);

        WALL_BLOCK_LIST.add(ModBlocks.MOSSY_STONE_BRICKS_MODERN);
        WALL_BLOCK_LIST.add(ModBlocks.MOSSY_STONE_BRICKS_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.MOSSY_STONE_BRICKS_CASTLE);

        WALL_BLOCK_LIST.add(ModBlocks.ANDESITE_MODERN);
        WALL_BLOCK_LIST.add(ModBlocks.ANDESITE_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.ANDESITE_CASTLE);

        WALL_BLOCK_LIST.add(ModBlocks.DIORITE_MODERN);
        WALL_BLOCK_LIST.add(ModBlocks.DIORITE_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.DIORITE_CASTLE);

        WALL_BLOCK_LIST.add(ModBlocks.GRANITE_MODERN);
        WALL_BLOCK_LIST.add(ModBlocks.GRANITE_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.GRANITE_CASTLE);

        WALL_BLOCK_LIST.add(ModBlocks.SANDSTONE_MODERN);
        WALL_BLOCK_LIST.add(ModBlocks.SANDSTONE_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.SANDSTONE_CASTLE);

        WALL_BLOCK_LIST.add(ModBlocks.RED_SANDSTONE_MODERN);
        WALL_BLOCK_LIST.add(ModBlocks.RED_SANDSTONE_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.RED_SANDSTONE_CASTLE);

        WALL_BLOCK_LIST.add(ModBlocks.BRICKS_MODERN);
        WALL_BLOCK_LIST.add(ModBlocks.BRICKS_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.BRICKS_CASTLE);

        WALL_BLOCK_LIST.add(ModBlocks.PRISMARINE_MODERN);
        WALL_BLOCK_LIST.add(ModBlocks.PRISMARINE_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.PRISMARINE_CASTLE);

        WALL_BLOCK_LIST.add(ModBlocks.NETHER_BRICKS_MODERN);
        WALL_BLOCK_LIST.add(ModBlocks.NETHER_BRICKS_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.NETHER_BRICKS_CASTLE);

        WALL_BLOCK_LIST.add(ModBlocks.RED_NETHER_BRICKS_MODERN);
        WALL_BLOCK_LIST.add(ModBlocks.RED_NETHER_BRICKS_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.RED_NETHER_BRICKS_CASTLE);

        WALL_BLOCK_LIST.add(ModBlocks.END_STONE_BRICKS_MODERN);
        WALL_BLOCK_LIST.add(ModBlocks.END_STONE_BRICKS_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.END_STONE_BRICKS_CASTLE);

        WALL_BLOCK_LIST.add(ModBlocks.BLACKSTONE_MODERN);
        WALL_BLOCK_LIST.add(ModBlocks.BLACKSTONE_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.BLACKSTONE_CASTLE);

        WALL_BLOCK_LIST.add(ModBlocks.POLISHED_BLACKSTONE_MODERN);
        WALL_BLOCK_LIST.add(ModBlocks.POLISHED_BLACKSTONE_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.POLISHED_BLACKSTONE_CASTLE);

        WALL_BLOCK_LIST.add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_MODERN);
        WALL_BLOCK_LIST.add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_CASTLE);

        WALL_BLOCK_LIST.add(ModBlocks.COBBLED_DEEPSLATE_MODERN);
        WALL_BLOCK_LIST.add(ModBlocks.COBBLED_DEEPSLATE_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.COBBLED_DEEPSLATE_CASTLE);

        WALL_BLOCK_LIST.add(ModBlocks.POLISHED_DEEPSLATE_MODERN);
        WALL_BLOCK_LIST.add(ModBlocks.POLISHED_DEEPSLATE_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.POLISHED_DEEPSLATE_CASTLE);

        WALL_BLOCK_LIST.add(ModBlocks.DEEPSLATE_BRICK_MODERN);
        WALL_BLOCK_LIST.add(ModBlocks.DEEPSLATE_BRICK_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.DEEPSLATE_BRICK_CASTLE);

        WALL_BLOCK_LIST.add(ModBlocks.DEEPSLATE_TILE_MODERN);
        WALL_BLOCK_LIST.add(ModBlocks.DEEPSLATE_TILE_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.DEEPSLATE_TILE_CASTLE);
        
        //END STONEWALLS AND BEGIN WOODENWALLS

        WALL_BLOCK_LIST.add(ModBlocks.OAK_WALL_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.BIRCH_WALL_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.SPRUCE_WALL_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.ACACIA_WALL_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.JUNGLE_WALL_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.DARKOAK_WALL_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.CRIMSON_WALL_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.WARPED_WALL_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.MANGROVE_WALL_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.BAMBOO_WALL_BUILDING);
        WALL_BLOCK_LIST.add(ModBlocks.CHERRY_WALL_BUILDING);

        
        //END WOODENWALLS
        
        return WALL_BLOCK_LIST;
    }

    public static ArrayList<Block> listOfMetalFenceBlocks() {

        ArrayList<Block> METAL_FENCE_BLOCK_LIST = new ArrayList<Block>();
        
        //BEGIN METALLFENCES

        METAL_FENCE_BLOCK_LIST.add(ModBlocks.COBBLESTONE_COPPER_FENCE);
        METAL_FENCE_BLOCK_LIST.add(ModBlocks.COBBLESTONE_EXPOSED_COPPER_FENCE);
        METAL_FENCE_BLOCK_LIST.add(ModBlocks.COBBLESTONE_WEATHERED_COPPER_FENCE);
        METAL_FENCE_BLOCK_LIST.add(ModBlocks.COBBLESTONE_OXIDIZED_COPPER_FENCE);

        METAL_FENCE_BLOCK_LIST.add(ModBlocks.COPPER_FENCE_GATE);
        METAL_FENCE_BLOCK_LIST.add(ModBlocks.EXPOSED_COPPER_FENCE_GATE);
        METAL_FENCE_BLOCK_LIST.add(ModBlocks.WEATHERED_COPPER_FENCE_GATE);
        METAL_FENCE_BLOCK_LIST.add(ModBlocks.OXIDIZED_COPPER_FENCE_GATE);

        METAL_FENCE_BLOCK_LIST.add(ModBlocks.COBBLESTONE_WAXED_COPPER_FENCE);
        METAL_FENCE_BLOCK_LIST.add(ModBlocks.COBBLESTONE_WAXED_EXPOSED_COPPER_FENCE);
        METAL_FENCE_BLOCK_LIST.add(ModBlocks.COBBLESTONE_WAXED_WEATHERED_COPPER_FENCE);
        METAL_FENCE_BLOCK_LIST.add(ModBlocks.COBBLESTONE_WAXED_OXIDIZED_COPPER_FENCE);

        METAL_FENCE_BLOCK_LIST.add(ModBlocks.WAXED_COPPER_FENCE_GATE);
        METAL_FENCE_BLOCK_LIST.add(ModBlocks.WAXED_EXPOSED_COPPER_FENCE_GATE);
        METAL_FENCE_BLOCK_LIST.add(ModBlocks.WAXED_WEATHERED_COPPER_FENCE_GATE);
        METAL_FENCE_BLOCK_LIST.add(ModBlocks.WAXED_OXIDIZED_COPPER_FENCE_GATE);

        METAL_FENCE_BLOCK_LIST.add(ModBlocks.COBBLESTONE_IRON_FENCE);
        METAL_FENCE_BLOCK_LIST.add(ModBlocks.COBBLESTONE_EXPOSED_IRON_FENCE);
        METAL_FENCE_BLOCK_LIST.add(ModBlocks.COBBLESTONE_WEATHERED_IRON_FENCE);
        METAL_FENCE_BLOCK_LIST.add(ModBlocks.COBBLESTONE_OXIDIZED_IRON_FENCE);

        METAL_FENCE_BLOCK_LIST.add(ModBlocks.IRON_FENCE_GATE);
        METAL_FENCE_BLOCK_LIST.add(ModBlocks.EXPOSED_IRON_FENCE_GATE);
        METAL_FENCE_BLOCK_LIST.add(ModBlocks.WEATHERED_IRON_FENCE_GATE);
        METAL_FENCE_BLOCK_LIST.add(ModBlocks.OXIDIZED_IRON_FENCE_GATE);

        METAL_FENCE_BLOCK_LIST.add(ModBlocks.COBBLESTONE_WAXED_IRON_FENCE);
        METAL_FENCE_BLOCK_LIST.add(ModBlocks.COBBLESTONE_WAXED_EXPOSED_IRON_FENCE);
        METAL_FENCE_BLOCK_LIST.add(ModBlocks.COBBLESTONE_WAXED_WEATHERED_IRON_FENCE);
        METAL_FENCE_BLOCK_LIST.add(ModBlocks.COBBLESTONE_WAXED_OXIDIZED_IRON_FENCE);

        METAL_FENCE_BLOCK_LIST.add(ModBlocks.WAXED_IRON_FENCE_GATE);
        METAL_FENCE_BLOCK_LIST.add(ModBlocks.WAXED_EXPOSED_IRON_FENCE_GATE);
        METAL_FENCE_BLOCK_LIST.add(ModBlocks.WAXED_WEATHERED_IRON_FENCE_GATE);
        METAL_FENCE_BLOCK_LIST.add(ModBlocks.WAXED_OXIDIZED_IRON_FENCE_GATE);

        METAL_FENCE_BLOCK_LIST.add(ModBlocks.COBBLESTONE_GOLD_FENCE);
        METAL_FENCE_BLOCK_LIST.add(ModBlocks.GOLD_FENCE_GATE);
        
        //END METALLFENCES

        return METAL_FENCE_BLOCK_LIST;
    }

    public static void threeTabs() {

            Registry.register(Registries.ITEM_GROUP, CUSTOMFENCE_WOOD_FENCE, FabricItemGroup.builder()
                .displayName(Text.translatable("itemGroup.customfence.tab_customfence_wooden_fence"))
                .icon(() -> new ItemStack(ModBlocks.SPRUCE_OAK_WILDLIFE))
                .entries((enabledFeatures, entries) -> {
                    for (Block block : listOfWoodFenceBlocks()) {
                        entries.add(block);
                    }
                })
                .build()
            );

            Registry.register(Registries.ITEM_GROUP, CUSTOMFENCE_WALL, FabricItemGroup.builder()
                .displayName(Text.translatable("itemGroup.customfence.tab_customfence_wall"))
                .icon(() -> new ItemStack(ModBlocks.STONE_MODERN))
                .entries((enabledFeatures, entries) -> {
                    for (Block block : listOfWallBlocks()) {
                        entries.add(block);
                    }
                })
                .build()
            );

            Registry.register(Registries.ITEM_GROUP, CUSTOMFENCE_METAL_FENCE, FabricItemGroup.builder()
                .displayName(Text.translatable("itemGroup.customfence.tab_customfence_metal_fence"))
                .icon(() -> new ItemStack(ModBlocks.COBBLESTONE_IRON_FENCE))
                .entries((enabledFeatures, entries) -> {
                    for (Block block : listOfMetalFenceBlocks()) {
                        entries.add(block);
                    }
                })
                .build()
            );

    };


    public static void oneTab() {

        Registry.register(Registries.ITEM_GROUP, CUSTOMFENCE, FabricItemGroup.builder()
                .displayName(Text.translatable("itemGroup.customfence.tab_customfence"))
                .icon(() -> new ItemStack(ModBlocks.SPRUCE_OAK_WILDLIFE))
                .entries((enabledFeatures, entries) -> {
                    for (Block block : listOfWoodFenceBlocks()) {
                        entries.add(block);
                    }
                    for (Block block : listOfWallBlocks()) {
                        entries.add(block);
                    }
                    for (Block block : listOfMetalFenceBlocks()) {
                        entries.add(block);
                    }
                })
                .build()
        );
    }

}
