package com.raptor.customfence_forge.init;

import com.raptor.customfence_forge.Main;
import com.raptor.customfence_forge.blocks.GlassFence;
import com.raptor.customfence_forge.blocks.GlassFenceGate;
import net.minecraft.core.BlockPos;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.properties.BlockSetType;
import net.minecraft.world.level.block.state.properties.WoodType;
import net.minecraftforge.eventbus.api.bus.BusGroup;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import java.util.function.Supplier;

public class ModBlocksGlassFence {

    public static final DeferredRegister<Block> GLASS_PLAIN_BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, Main.MOD_ID);

    public static final RegistryObject<Block> WHITE_CONCRETE_GLASS_PLAIN = registerBlock("white_concrete_glass_plain", () -> new GlassFence(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("white_concrete_glass_plain"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS)));
    public static final RegistryObject<Block> WHITE_CONCRETE_WHITE_STAINED_GLASS_PLAIN = registerBlock("white_concrete_white_stained_glass_plain", () -> new GlassFence(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("white_concrete_white_stained_glass_plain"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS)));
    public static final RegistryObject<Block> WHITE_CONCRETE_LIGHT_GRAY_STAINED_GLASS_PLAIN = registerBlock("white_concrete_light_gray_stained_glass_plain", () -> new GlassFence(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("white_concrete_light_gray_stained_glass_plain"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS)));
    public static final RegistryObject<Block> WHITE_CONCRETE_GRAY_STAINED_GLASS_PLAIN = registerBlock("white_concrete_gray_stained_glass_plain", () -> new GlassFence(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("white_concrete_gray_stained_glass_plain"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS)));
    public static final RegistryObject<Block> WHITE_CONCRETE_BLACK_STAINED_GLASS_PLAIN = registerBlock("white_concrete_black_stained_glass_plain", () -> new GlassFence(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("white_concrete_black_stained_glass_plain"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS)));
    public static final RegistryObject<Block> WHITE_CONCRETE_BROWN_STAINED_GLASS_PLAIN = registerBlock("white_concrete_brown_stained_glass_plain", () -> new GlassFence(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("white_concrete_brown_stained_glass_plain"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS)));
    public static final RegistryObject<Block> WHITE_CONCRETE_RED_STAINED_GLASS_PLAIN = registerBlock("white_concrete_red_stained_glass_plain", () -> new GlassFence(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("white_concrete_red_stained_glass_plain"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS)));
    public static final RegistryObject<Block> WHITE_CONCRETE_ORANGE_STAINED_GLASS_PLAIN = registerBlock("white_concrete_orange_stained_glass_plain", () -> new GlassFence(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("white_concrete_orange_stained_glass_plain"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS)));
    public static final RegistryObject<Block> WHITE_CONCRETE_YELLOW_STAINED_GLASS_PLAIN = registerBlock("white_concrete_yellow_stained_glass_plain", () -> new GlassFence(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("white_concrete_yellow_stained_glass_plain"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS)));
    public static final RegistryObject<Block> WHITE_CONCRETE_LIME_STAINED_GLASS_PLAIN = registerBlock("white_concrete_lime_stained_glass_plain", () -> new GlassFence(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("white_concrete_lime_stained_glass_plain"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS)));
    public static final RegistryObject<Block> WHITE_CONCRETE_GREEN_STAINED_GLASS_PLAIN = registerBlock("white_concrete_green_stained_glass_plain", () -> new GlassFence(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("white_concrete_green_stained_glass_plain"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS)));
    public static final RegistryObject<Block> WHITE_CONCRETE_CYAN_STAINED_GLASS_PLAIN = registerBlock("white_concrete_cyan_stained_glass_plain", () -> new GlassFence(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("white_concrete_cyan_stained_glass_plain"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS)));
    public static final RegistryObject<Block> WHITE_CONCRETE_LIGHT_BLUE_STAINED_GLASS_PLAIN = registerBlock("white_concrete_light_blue_stained_glass_plain", () -> new GlassFence(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("white_concrete_light_blue_stained_glass_plain"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS)));
    public static final RegistryObject<Block> WHITE_CONCRETE_BLUE_STAINED_GLASS_PLAIN = registerBlock("white_concrete_blue_stained_glass_plain", () -> new GlassFence(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("white_concrete_blue_stained_glass_plain"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS)));
    public static final RegistryObject<Block> WHITE_CONCRETE_PURPLE_STAINED_GLASS_PLAIN = registerBlock("white_concrete_purple_stained_glass_plain", () -> new GlassFence(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("white_concrete_purple_stained_glass_plain"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS)));
    public static final RegistryObject<Block> WHITE_CONCRETE_MAGENTA_STAINED_GLASS_PLAIN = registerBlock("white_concrete_magenta_stained_glass_plain", () -> new GlassFence(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("white_concrete_magenta_stained_glass_plain"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS)));
    public static final RegistryObject<Block> WHITE_CONCRETE_PINK_STAINED_GLASS_PLAIN = registerBlock("white_concrete_pink_stained_glass_plain", () -> new GlassFence(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("white_concrete_pink_stained_glass_plain"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS)));

    public static final RegistryObject<Block> GLASS_PLAIN_FENCE_GATE = registerBlock("glass_plain_fence_gate", () -> new GlassFenceGate(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("glass_plain_fence_gate"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS), new WoodType("metal", BlockSetType.IRON, SoundType.METAL, SoundType.METAL, SoundEvents.IRON_DOOR_CLOSE, SoundEvents.IRON_DOOR_OPEN)));
    public static final RegistryObject<Block> WHITE_STAINED_GLASS_PLAIN_FENCE_GATE = registerBlock("white_stained_glass_plain_fence_gate", () -> new GlassFenceGate(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("white_stained_glass_plain_fence_gate"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS), new WoodType("metal", BlockSetType.IRON, SoundType.METAL, SoundType.METAL, SoundEvents.IRON_DOOR_CLOSE, SoundEvents.IRON_DOOR_OPEN)));
    public static final RegistryObject<Block> LIGHT_GRAY_STAINED_GLASS_PLAIN_FENCE_GATE = registerBlock("light_gray_stained_glass_plain_fence_gate", () -> new GlassFenceGate(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("light_gray_stained_glass_plain_fence_gate"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS), new WoodType("metal", BlockSetType.IRON, SoundType.METAL, SoundType.METAL, SoundEvents.IRON_DOOR_CLOSE, SoundEvents.IRON_DOOR_OPEN)));
    public static final RegistryObject<Block> GRAY_STAINED_GLASS_PLAIN_FENCE_GATE = registerBlock("gray_stained_glass_plain_fence_gate", () -> new GlassFenceGate(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("gray_stained_glass_plain_fence_gate"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS), new WoodType("metal", BlockSetType.IRON, SoundType.METAL, SoundType.METAL, SoundEvents.IRON_DOOR_CLOSE, SoundEvents.IRON_DOOR_OPEN)));
    public static final RegistryObject<Block> BLACK_STAINED_GLASS_PLAIN_FENCE_GATE = registerBlock("black_stained_glass_plain_fence_gate", () -> new GlassFenceGate(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("black_stained_glass_plain_fence_gate"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS), new WoodType("metal", BlockSetType.IRON, SoundType.METAL, SoundType.METAL, SoundEvents.IRON_DOOR_CLOSE, SoundEvents.IRON_DOOR_OPEN)));
    public static final RegistryObject<Block> BROWN_STAINED_GLASS_PLAIN_FENCE_GATE = registerBlock("brown_stained_glass_plain_fence_gate", () -> new GlassFenceGate(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("brown_stained_glass_plain_fence_gate"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS), new WoodType("metal", BlockSetType.IRON, SoundType.METAL, SoundType.METAL, SoundEvents.IRON_DOOR_CLOSE, SoundEvents.IRON_DOOR_OPEN)));
    public static final RegistryObject<Block> RED_STAINED_GLASS_PLAIN_FENCE_GATE = registerBlock("red_stained_glass_plain_fence_gate", () -> new GlassFenceGate(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("red_stained_glass_plain_fence_gate"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS), new WoodType("metal", BlockSetType.IRON, SoundType.METAL, SoundType.METAL, SoundEvents.IRON_DOOR_CLOSE, SoundEvents.IRON_DOOR_OPEN)));
    public static final RegistryObject<Block> ORANGE_STAINED_GLASS_PLAIN_FENCE_GATE = registerBlock("orange_stained_glass_plain_fence_gate", () -> new GlassFenceGate(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("orange_stained_glass_plain_fence_gate"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS), new WoodType("metal", BlockSetType.IRON, SoundType.METAL, SoundType.METAL, SoundEvents.IRON_DOOR_CLOSE, SoundEvents.IRON_DOOR_OPEN)));
    public static final RegistryObject<Block> YELLOW_STAINED_GLASS_PLAIN_FENCE_GATE = registerBlock("yellow_stained_glass_plain_fence_gate", () -> new GlassFenceGate(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("yellow_stained_glass_plain_fence_gate"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS), new WoodType("metal", BlockSetType.IRON, SoundType.METAL, SoundType.METAL, SoundEvents.IRON_DOOR_CLOSE, SoundEvents.IRON_DOOR_OPEN)));
    public static final RegistryObject<Block> LIME_STAINED_GLASS_PLAIN_FENCE_GATE = registerBlock("lime_stained_glass_plain_fence_gate", () -> new GlassFenceGate(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("lime_stained_glass_plain_fence_gate"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS), new WoodType("metal", BlockSetType.IRON, SoundType.METAL, SoundType.METAL, SoundEvents.IRON_DOOR_CLOSE, SoundEvents.IRON_DOOR_OPEN)));
    public static final RegistryObject<Block> GREEN_STAINED_GLASS_PLAIN_FENCE_GATE = registerBlock("green_stained_glass_plain_fence_gate", () -> new GlassFenceGate(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("green_stained_glass_plain_fence_gate"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS), new WoodType("metal", BlockSetType.IRON, SoundType.METAL, SoundType.METAL, SoundEvents.IRON_DOOR_CLOSE, SoundEvents.IRON_DOOR_OPEN)));
    public static final RegistryObject<Block> CYAN_STAINED_GLASS_PLAIN_FENCE_GATE = registerBlock("cyan_stained_glass_plain_fence_gate", () -> new GlassFenceGate(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("cyan_stained_glass_plain_fence_gate"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS), new WoodType("metal", BlockSetType.IRON, SoundType.METAL, SoundType.METAL, SoundEvents.IRON_DOOR_CLOSE, SoundEvents.IRON_DOOR_OPEN)));
    public static final RegistryObject<Block> LIGHT_BLUE_STAINED_GLASS_PLAIN_FENCE_GATE = registerBlock("light_blue_stained_glass_plain_fence_gate", () -> new GlassFenceGate(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("light_blue_stained_glass_plain_fence_gate"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS), new WoodType("metal", BlockSetType.IRON, SoundType.METAL, SoundType.METAL, SoundEvents.IRON_DOOR_CLOSE, SoundEvents.IRON_DOOR_OPEN)));
    public static final RegistryObject<Block> BLUE_STAINED_GLASS_PLAIN_FENCE_GATE = registerBlock("blue_stained_glass_plain_fence_gate", () -> new GlassFenceGate(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("blue_stained_glass_plain_fence_gate"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS), new WoodType("metal", BlockSetType.IRON, SoundType.METAL, SoundType.METAL, SoundEvents.IRON_DOOR_CLOSE, SoundEvents.IRON_DOOR_OPEN)));
    public static final RegistryObject<Block> PURPLE_STAINED_GLASS_PLAIN_FENCE_GATE = registerBlock("purple_stained_glass_plain_fence_gate", () -> new GlassFenceGate(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("purple_stained_glass_plain_fence_gate"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS), new WoodType("metal", BlockSetType.IRON, SoundType.METAL, SoundType.METAL, SoundEvents.IRON_DOOR_CLOSE, SoundEvents.IRON_DOOR_OPEN)));
    public static final RegistryObject<Block> MAGENTA_STAINED_GLASS_PLAIN_FENCE_GATE = registerBlock("magenta_stained_glass_plain_fence_gate", () -> new GlassFenceGate(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("magenta_stained_glass_plain_fence_gate"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS), new WoodType("metal", BlockSetType.IRON, SoundType.METAL, SoundType.METAL, SoundEvents.IRON_DOOR_CLOSE, SoundEvents.IRON_DOOR_OPEN)));
    public static final RegistryObject<Block> PINK_STAINED_GLASS_PLAIN_FENCE_GATE = registerBlock("pink_stained_glass_plain_fence_gate", () -> new GlassFenceGate(Block.Properties.ofFullCopy(Blocks.GLASS).setId((GLASS_PLAIN_BLOCKS.key("pink_stained_glass_plain_fence_gate"))).noCollision().isValidSpawn(ModBlocksGlassFence::never).isRedstoneConductor(ModBlocksGlassFence::isntSolid).isSuffocating(ModBlocksGlassFence::isntSolid).isViewBlocking(ModBlocksGlassFence::isntSolid).strength(2.0f, 3.0f).sound(SoundType.GLASS), new WoodType("metal", BlockSetType.IRON, SoundType.METAL, SoundType.METAL, SoundEvents.IRON_DOOR_CLOSE, SoundEvents.IRON_DOOR_OPEN)));

    private static <T extends Block> RegistryObject<T> registerBlock(String name, Supplier<T> block) {
        RegistryObject<T> toReturn = GLASS_PLAIN_BLOCKS.register(name, block);
        registerBlockItem(name, toReturn);
        return toReturn;
    }

    private static <T extends Block> void registerBlockItem(String name, RegistryObject<T> block) {
        ModItems.ITEMS.register(name, () -> new BlockItem(block.get(), new Item.Properties().useBlockDescriptionPrefix()
                .setId(ModItems.ITEMS.key(name))));
    }

    public static void register(BusGroup eventBus) {
        GLASS_PLAIN_BLOCKS.register(eventBus);
    }

    private static boolean never(BlockState state, BlockGetter getter, BlockPos pos) {
        return false;
    }

    private static Boolean never(BlockState state, BlockGetter getter, BlockPos pos, EntityType<?> entity) {
        return false;
    }
    private static boolean isntSolid(BlockState state, BlockGetter getter, BlockPos pos) {
        return false;
    }

}
